apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "test"
  description: "test"
  annotations:
    github.com/project-slug: "kbeauregard/test"
    backstage.io/techdocs-ref: github:https://github.com/kbeauregard/test
spec:
  type: documentation
  lifecycle: experimental
  owner: "kbeauregard"
